server:
  port: 1111
  session.timeout: 1800

spring.datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.1.207:3306/gx?useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: Zjm123456!
    driver-class-name: com.mysql.jdbc.Driver
spring.freemarker:
    suffix: .ftl